%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(beringei_types).

-include("beringei_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info(_) -> erlang:error(function_clause).

struct_info_ext(_) -> erlang:error(function_clause).

