%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(beringei_data_types).

-include("beringei_data_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Key') ->
  {struct, [{1, string},
          {2, i64}]}
;

struct_info('TimeSeriesBlock') ->
  {struct, [{1, i32},
          {2, i32},
          {3, string}]}
;

struct_info('TimeSeriesData') ->
  {struct, [{1, {list, {struct, {'beringei_data_types', 'TimeSeriesBlock'}}}},
          {2, i32}]}
;

struct_info('GetDataRequest') ->
  {struct, [{1, {list, {struct, {'beringei_data_types', 'Key'}}}},
          {2, i64},
          {3, i64}]}
;

struct_info('GetDataResult') ->
  {struct, [{1, {list, {struct, {'beringei_data_types', 'TimeSeriesData'}}}}]}
;

struct_info('TimeValuePair') ->
  {struct, [{1, i64},
          {2, double}]}
;

struct_info('DataPoint') ->
  {struct, [{1, {struct, {'beringei_data_types', 'Key'}}},
          {2, {struct, {'beringei_data_types', 'TimeValuePair'}}},
          {3, i32}]}
;

struct_info('PutDataRequest') ->
  {struct, [{1, {list, {struct, {'beringei_data_types', 'DataPoint'}}}}]}
;

struct_info('PutDataResult') ->
  {struct, [{1, {list, {struct, {'beringei_data_types', 'DataPoint'}}}}]}
;

struct_info('GetShardDataBucketResult') ->
  {struct, [{1, i32},
          {2, {list, string}},
          {3, {list, {list, {struct, {'beringei_data_types', 'TimeSeriesBlock'}}}}},
          {4, {list, bool}},
          {5, bool}]}
;

struct_info('ShardInfo') ->
  {struct, [{1, i32},
          {2, string},
          {3, i32}]}
;

struct_info('ServiceMap') ->
  {struct, [{1, string},
          {2, string},
          {3, bool},
          {4, {list, {struct, {'beringei_data_types', 'ShardInfo'}}}}]}
;

struct_info('ConfigurationInfo') ->
  {struct, [{1, i32},
          {2, {list, {struct, {'beringei_data_types', 'ServiceMap'}}}}]}
;

struct_info('GetLastUpdateTimesRequest') ->
  {struct, [{1, i64},
          {2, i32},
          {3, i32},
          {4, i32}]}
;

struct_info('KeyUpdateTime') ->
  {struct, [{1, string},
          {2, i32},
          {3, i32},
          {4, bool}]}
;

struct_info('GetLastUpdateTimesResult') ->
  {struct, [{1, {list, {struct, {'beringei_data_types', 'KeyUpdateTime'}}}},
          {2, bool}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Key') ->
  {struct, [{1, undefined, string, 'key', undefined},
          {2, undefined, i64, 'shardId', undefined}]}
;

struct_info_ext('TimeSeriesBlock') ->
  {struct, [{1, undefined, i32, 'compression', undefined},
          {2, undefined, i32, 'count', undefined},
          {3, undefined, string, 'data', undefined}]}
;

struct_info_ext('TimeSeriesData') ->
  {struct, [{1, undefined, {list, {struct, {'beringei_data_types', 'TimeSeriesBlock'}}}, 'data', []},
          {2, undefined, i32, 'status',   0}]}
;

struct_info_ext('GetDataRequest') ->
  {struct, [{1, undefined, {list, {struct, {'beringei_data_types', 'Key'}}}, 'keys', []},
          {2, undefined, i64, 'begin', undefined},
          {3, undefined, i64, 'end', undefined}]}
;

struct_info_ext('GetDataResult') ->
  {struct, [{1, undefined, {list, {struct, {'beringei_data_types', 'TimeSeriesData'}}}, 'results', []}]}
;

struct_info_ext('TimeValuePair') ->
  {struct, [{1, undefined, i64, 'unixTime', undefined},
          {2, undefined, double, 'value', undefined}]}
;

struct_info_ext('DataPoint') ->
  {struct, [{1, undefined, {struct, {'beringei_data_types', 'Key'}}, 'key', #'Key'{}},
          {2, undefined, {struct, {'beringei_data_types', 'TimeValuePair'}}, 'value', #'TimeValuePair'{}},
          {3, undefined, i32, 'categoryId', undefined}]}
;

struct_info_ext('PutDataRequest') ->
  {struct, [{1, undefined, {list, {struct, {'beringei_data_types', 'DataPoint'}}}, 'data', []}]}
;

struct_info_ext('PutDataResult') ->
  {struct, [{1, undefined, {list, {struct, {'beringei_data_types', 'DataPoint'}}}, 'data', []}]}
;

struct_info_ext('GetShardDataBucketResult') ->
  {struct, [{1, undefined, i32, 'status', undefined},
          {2, undefined, {list, string}, 'keys', []},
          {3, undefined, {list, {list, {struct, {'beringei_data_types', 'TimeSeriesBlock'}}}}, 'data', []},
          {4, undefined, {list, bool}, 'recentRead', []},
          {5, undefined, bool, 'moreEntries', undefined}]}
;

struct_info_ext('ShardInfo') ->
  {struct, [{1, undefined, i32, 'shardId', undefined},
          {2, undefined, string, 'hostAddress', undefined},
          {3, undefined, i32, 'port', undefined}]}
;

struct_info_ext('ServiceMap') ->
  {struct, [{1, undefined, string, 'serviceName', undefined},
          {2, undefined, string, 'location', undefined},
          {3, undefined, bool, 'isLoggingNewKeysEnabled', undefined},
          {4, undefined, {list, {struct, {'beringei_data_types', 'ShardInfo'}}}, 'shardMap', []}]}
;

struct_info_ext('ConfigurationInfo') ->
  {struct, [{1, undefined, i32, 'shardCount', undefined},
          {2, undefined, {list, {struct, {'beringei_data_types', 'ServiceMap'}}}, 'serviceMap', []}]}
;

struct_info_ext('GetLastUpdateTimesRequest') ->
  {struct, [{1, undefined, i64, 'shardId', undefined},
          {2, undefined, i32, 'minLastUpdateTime', undefined},
          {3, undefined, i32, 'offset', undefined},
          {4, undefined, i32, 'limit', undefined}]}
;

struct_info_ext('KeyUpdateTime') ->
  {struct, [{1, undefined, string, 'key', undefined},
          {2, undefined, i32, 'categoryId', undefined},
          {3, undefined, i32, 'updateTime', undefined},
          {4, undefined, bool, 'queriedRecently', undefined}]}
;

struct_info_ext('GetLastUpdateTimesResult') ->
  {struct, [{1, undefined, {list, {struct, {'beringei_data_types', 'KeyUpdateTime'}}}, 'keys', []},
          {2, undefined, bool, 'moreResults', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

