%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(beringei_service_thrift).
-behaviour(thrift_service).


-include("beringei_service_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% getData(This, Req)
function_info('getData', params_type) ->
  {struct, [{1, {struct, {'beringei_data_types', 'GetDataRequest'}}}]}
;
function_info('getData', reply_type) ->
  {struct, {'beringei_data_types', 'GetDataResult'}};
function_info('getData', exceptions) ->
  {struct, []}
;
% putDataPoints(This, Req)
function_info('putDataPoints', params_type) ->
  {struct, [{1, {struct, {'beringei_data_types', 'PutDataRequest'}}}]}
;
function_info('putDataPoints', reply_type) ->
  {struct, {'beringei_data_types', 'PutDataResult'}};
function_info('putDataPoints', exceptions) ->
  {struct, []}
;
% getShardDataBucket(This, Begin, End, ShardId, Offset, Limit)
function_info('getShardDataBucket', params_type) ->
  {struct, [{1, i64},
          {2, i64},
          {3, i64},
          {4, i32},
          {5, i32}]}
;
function_info('getShardDataBucket', reply_type) ->
  {struct, {'beringei_data_types', 'GetShardDataBucketResult'}};
function_info('getShardDataBucket', exceptions) ->
  {struct, []}
;
% getLastUpdateTimes(This, Req)
function_info('getLastUpdateTimes', params_type) ->
  {struct, [{1, {struct, {'beringei_data_types', 'GetLastUpdateTimesRequest'}}}]}
;
function_info('getLastUpdateTimes', reply_type) ->
  {struct, {'beringei_data_types', 'GetLastUpdateTimesResult'}};
function_info('getLastUpdateTimes', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

